### ISSUE TITLE
Why is the package "fileutils"?

### ISSUE THREAD

**Issue by scothis** [pivotal/go-ape#9]
Looking at a downstream project, I was very confused about where the fileutils symbol was coming from when the package import was github.com/pivotal/go-ape. The convention in go is for the package name to match the directory name.

If keeping the `fileutils` package is important, I suggest creating a fileutils directory and moving all of the *.go files into that directory.

**Comment by glyn** [comment]
I agree this is confusing. (See [Almost everything about imports](https://scene-si.org/2018/01/25/go-tips-and-tricks-almost-everything-about-imports/) under "Package names vs. package imports" for an explanation of how it works.)

@sbawaska and I have agreed to introduce `pkg/furl` and `pkg/filecopy` directories, to make the package name and the package import and avoid confusion.
